---
apiVersion: v1
kind: Namespace
metadata:
  name: travel-advisor
  labels:
    name: travel-advisor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-advisor
  namespace: travel-advisor
spec:
  selector:
    matchLabels:
      name: travel-advisor
  template:
    metadata:
      labels:
        name: travel-advisor
    spec:
      containers:
        - name: travel-advisor
          image: thisthatdc/travel-advisor:v0.3.0-bedrock
          env:
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: secret
            - name: AWS_EMBEDDING_MODEL
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: embedding
            - name: AWS_MODEL
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: model
            - name: AWS_GUARDRAIL_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: guardrail
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets
              readOnly: true
              mountPath: "/etc/secrets"
      volumes:
        - name: secrets
          projected:
            sources:
              - secret:
                  name: dynatrace
              - secret:
                  name: aws
---
apiVersion: v1
kind: Service
metadata:
  name: travel-advisor
  namespace: travel-advisor
spec:
  type: NodePort
  selector:
    name: travel-advisor
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
      nodePort: 30100
